# Generated by Django 5.1.1 on 2024-09-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='Book Title', max_length=200),
        ),
    ]
